Added tons of stuff... many build scripts may not work yet

diff --git a/build-scripts/build-autoconf b/build-scripts/build-autoconf
--- a/build-scripts/build-autoconf
+++ b/build-scripts/build-autoconf
@@ -1,28 +1,37 @@
 #!/usr/bin/ksh
 
-full_path=http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
-suffix=.tar.gz
-package_name=${full_path##*/}
-export basedir_bit=${package_name%${suffix}}
+# Should need to set only this variable
+export full_path=http://ftp.gnu.org/gnu/autoconf/autoconf-2.64.tar.gz
 
-# The if gives us a way to terminate the script if we are debugging
-# Setup by having Setup exit with a non-zero status.
-if ! . "${0%/*}/Setup" ; then
-    exit 1
-fi
-mk_dir_structure
+. "${0%/*}/BaseSetup"
 
+# basename of what we are going to fetch
+export package_name="${full_path##*/}"
+
+# fetch the package
 cd ${image_dir}
 if [[ ! -r "${package_name}" ]] ; then
   wget ${full_path}
 fi
 
+# Figure out what basedir this will produce
+export basedir_bit="$( get_basedir_bit "${package_name}" )"
+echo "basedir is ${basedir_bit}"
+
+# The if gives us a way to terminate the script if we are debugging
+# Setup by having Setup exit with a non-zero status.
+if ! . "${build_scripts}/Setup" ; then
+    exit 1
+fi
+mk_dir_structure
+
+# 6 failures in 2.64
+#  Check &&
+
 Unpack &&
-  mkdir -p "${build_dir}" &&
   cd "${build_dir}" &&
   Patch &&
   Configure &&
   Make &&
-  Check &&
   Package &&
   Install
